baseURL: 'https://phoebezn.github.io/'
languageCode: 'zh'
title: 'è²æ¯”çš„ç©ºé—´'
theme: ['PaperMod']

buildDrafts: false

menu:
  main:
    - identifier: categories
      name: ç±»åˆ«
      url: /categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾
      url: /tags/
      weight: 20
params:
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: ä½ å¥½ ğŸ‘‹
    Content: æ¬¢è¿æ¥åˆ°è²æ¯”å’Œç‹—ç‹—çš„ç©ºé—´...

  socialIcons: # optional
    - name: github
      title: View Source on Github
      url: "https://github.com/phoebezn/phoebezn.github.io"

    - name: mastodon
      title: é•¿æ¯›è±¡
      url: "https://m.cmx.im/@phoebeZ"
caches:
  images:
    dir: :cacheDir/images