baseURL: 'https://phoebezn.github.io/'
languageCode: 'zh'
title: 'è²æ¯”çš„ç©ºé—´'
theme: ['PaperMod']
menu:
  main:
    - identifier: categories
      name: ç±»åˆ«
      url: /categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾
      url: /tags/
      weight: 20
params:
  ShowToc: true
  TocOpen: true
  homeInfoParams:
    Title: ä½ å¥½ ğŸ‘‹
    Content: æ¬¢è¿æ¥åˆ°è²æ¯”çš„ç©ºé—´...

  socialIcons: # optional
    - name: github
      title: View Source on Github
      url: "https://github.com/phoebezn/first-blog"